### ISSUE TITLE
Install script is failing

### ISSUE THREAD

**Issue by dipaladu369** [hallowelt/docker-bluespice-wiki#34]
The script root-fs/app/bin/run-installation is failing due to typo.

details:

https://github.com/hallowelt/docker-bluespice-wiki/blob/main/root-fs/app/bin/run-installation#L50-L51 should be like

		-keyout /data/simplesamlphp/certs/saml.pem \
		-subj "/CN=$WIKI_HOST"

and the extra s in the password file name.

https://github.com/hallowelt/docker-bluespice-wiki/blob/main/root-fs/app/bin/run-installation#L62

**Comment by osnard** [comment]
Fixed by https://github.com/hallowelt/docker-bluespice-wiki/pull/35
